"""Build the WordPress-123.com form upload set. FTP I/O stays in the script."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
FORM_DIR = ROOT / "web" / "wordpress-form"
STATIC_FILES = (
    "index.php",
    "submit.php",
    "fetch.php",
    "common.php",
    ".htaccess",
    "data/.htaccess",
    "signature.txt",
)
PLACEHOLDER_TOKEN = "replace-this-intake-token"


def remote_store_target(remote_dir: str, relative: str) -> tuple[str, str]:
    """Return (directory to cwd into, filename to STOR)."""
    remote_dir = remote_dir.replace("\\", "/").strip("/")
    relative = relative.replace("\\", "/").strip("/")
    if "/" in relative:
        subdir, name = relative.rsplit("/", 1)
        directory = f"{remote_dir}/{subdir}" if remote_dir else subdir
    else:
        name = relative
        directory = remote_dir
    return directory, name


def _php_quote(value: str) -> str:
    return (value or "").replace("\\", "\\\\").replace("'", "\\'")


def render_config_php(token: str, notify: dict[str, str] | None = None) -> bytes:
    lines = [
        "<?php",
        "// Generated by deploy_wordpress_form. Do not commit.",
        f"define('INTAKE_TOKEN', '{_php_quote(token)}');",
    ]
    if notify:
        lines.extend(
            [
                f"define('NOTIFY_TO', '{_php_quote(notify.get('to', ''))}');",
                f"define('NOTIFY_FROM', '{_php_quote(notify.get('from', ''))}');",
                f"define('NOTIFY_PASSWORD', '{_php_quote(notify.get('password', ''))}');",
                f"define('NOTIFY_SMTP_HOST', '{_php_quote(notify.get('host', ''))}');",
                f"define('NOTIFY_SMTP_PORT', {int(notify.get('port') or 587)});",
            ]
        )
    lines.append("")
    return ("\n".join(lines)).encode("utf-8")


def collect_uploads(token: str) -> list[tuple[str, bytes]]:
    token = (token or "").strip()
    if not token or token == PLACEHOLDER_TOKEN:
        raise ValueError("WORDPRESS_INTAKE_TOKEN is missing.")
    uploads: list[tuple[str, bytes]] = []
    for relative in STATIC_FILES:
        path = FORM_DIR / relative
        if not path.is_file():
            raise FileNotFoundError(relative)
        uploads.append((relative.replace("\\", "/"), path.read_bytes()))
    notify = None
    try:
        from moriyama_mail.notify.mailer import shared_notify_settings

        notify = shared_notify_settings()
    except Exception:
        notify = None
    uploads.append(("config.php", render_config_php(token, notify)))
    return uploads
