"""Build the WordPress-123.com form upload set. FTP I/O stays in the script."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
FORM_DIR = ROOT / "web" / "wordpress-form"
STATIC_FILES = (
    "index.php",
    "submit.php",
    "fetch.php",
    "common.php",
    ".htaccess",
    "data/.htaccess",
)
PLACEHOLDER_TOKEN = "replace-this-intake-token"


def remote_store_target(remote_dir: str, relative: str) -> tuple[str, str]:
    """Return (directory to cwd into, filename to STOR)."""
    remote_dir = remote_dir.replace("\\", "/").strip("/")
    relative = relative.replace("\\", "/").strip("/")
    if "/" in relative:
        subdir, name = relative.rsplit("/", 1)
        directory = f"{remote_dir}/{subdir}" if remote_dir else subdir
    else:
        name = relative
        directory = remote_dir
    return directory, name


def render_config_php(token: str) -> bytes:
    safe = token.replace("\\", "\\\\").replace("'", "\\'")
    return (
        "<?php\n"
        "// Generated by deploy_wordpress_form. Do not commit.\n"
        f"define('INTAKE_TOKEN', '{safe}');\n"
    ).encode("utf-8")


def collect_uploads(token: str) -> list[tuple[str, bytes]]:
    token = (token or "").strip()
    if not token or token == PLACEHOLDER_TOKEN:
        raise ValueError("WORDPRESS_INTAKE_TOKEN is missing.")
    uploads: list[tuple[str, bytes]] = []
    for relative in STATIC_FILES:
        path = FORM_DIR / relative
        if not path.is_file():
            raise FileNotFoundError(relative)
        uploads.append((relative.replace("\\", "/"), path.read_bytes()))
    uploads.append(("config.php", render_config_php(token)))
    return uploads
